__version__ = "1.1.0"

from .nodes import (
    NODE_CLASS_MAPPINGS as EAGLE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as EAGLE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .video_preview import (
    NODE_CLASS_MAPPINGS as VIDEO_PREVIEW_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as VIDEO_PREVIEW_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **EAGLE_NODE_CLASS_MAPPINGS,
    **VIDEO_PREVIEW_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **EAGLE_NODE_DISPLAY_NAME_MAPPINGS,
    **VIDEO_PREVIEW_NODE_DISPLAY_NAME_MAPPINGS,
}

WEB_DIRECTORY = "./web"

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
    "WEB_DIRECTORY",
]
